[/Script/EngineSettings.GameMapsSettings]
GameDefaultMap=/Game/Maps/L_TestDistrict.L_TestDistrict
ServerDefaultMap=/Game/Maps/L_TestDistrict.L_TestDistrict
EditorStartupMap=/Game/Maps/L_TestDistrict.L_TestDistrict
GlobalDefaultGameMode=/Script/PuffersClub.PCGameMode

[/Script/Engine.Engine]
GameEngine=/Script/Engine.GameEngine

[/Script/Engine.RendererSettings]
r.GenerateMeshDistanceFields=True
r.DynamicGlobalIlluminationMethod=1
r.ReflectionMethod=1
r.Nanite.ProjectEnabled=True
r.Shadow.Virtual.Enable=1

[/Script/WorldPartitionEditor.WorldPartitionEditorSettings]
CommandletClass=Class'/Script/UnrealEd.WorldPartitionConvertCommandlet'

[/Script/Engine.GameNetworkManager]
TotalNetBandwidth=600000
MaxDynamicBandwidth=40000
MinDynamicBandwidth=8000

[OnlineSubsystem]
DefaultPlatformService=Null
; Switch to Steam for shipping builds:
; DefaultPlatformService=Steam

[OnlineSubsystemSteam]
bEnabled=false
SteamDevAppId=480

[/Script/OnlineSubsystemUtils.IpNetDriver]
NetServerMaxTickRate=30
MaxNetTickRate=60
MaxClientRate=100000
MaxInternetClientRate=100000
